apiVersion: v1
kind: Namespace
metadata:
  name: torrenttools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
  namespace: torrenttools
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        imagePullPolicy: IfNotPresent
        ports:
        - port: 9091
          name: transmission9091tcp
          protocol: TCP
        - port: 51413
          name: transmission51413tcp
          protocol: TCP
        - port: 51413
          name: transmission51413udp
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-tcp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: transmission
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
  - port: 51413
    targetPort: 51413
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
---
apiVersion: v1
kind: Service
metadata:
  name: transmission-udp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: transmission
  ports:
  - port: 51413
    targetPort: 51413
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: torrenttools
spec:
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: IfNotPresent
        ports:
        - port: 8989
          name: sonarr8989tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-tcp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: sonarr
  ports:
  - port: 8989
    targetPort: 8989
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: torrenttools
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr
        imagePullPolicy: IfNotPresent
        ports:
        - port: 7878
          name: radarr7878tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-tcp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: radarr
  ports:
  - port: 7878
    targetPort: 7878
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jackett
  name: jackett
  namespace: torrenttools
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett
        imagePullPolicy: IfNotPresent
        ports:
        - port: 9117
          name: jackett9117tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-tcp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: jackett
  ports:
  - port: 9117
    targetPort: 9117
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ombi
  name: ombi
  namespace: torrenttools
spec:
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      containers:
      - name: ombi
        image: linuxserver/ombi
        imagePullPolicy: IfNotPresent
        ports:
        - port: 3579
          name: ombi3579tcp
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ombi-tcp
  namespace: torrenttools
  annotations:
    metallb.universe.tf/allow-shared-ip: torrenttools
spec:
  selector:
    app: ombi
  ports:
  - port: 3579
    targetPort: 3579
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  allocateLoadBalancerNodePorts: false
